export const INVENTORY_TRANSACTION_TYPES = Object.freeze({
  OPENING_STOCK: "OPENING_STOCK",
  STOCK_IN: "STOCK_IN",
  STOCK_OUT: "STOCK_OUT",
  GOODS_RECEIPT: "GOODS_RECEIPT",
  ADJUSTMENT_INCREASE: "ADJUSTMENT_INCREASE",
  ADJUSTMENT_DECREASE: "ADJUSTMENT_DECREASE",
  RETURN_IN: "RETURN_IN",
  RETURN_OUT: "RETURN_OUT",
  VOID: "VOID",
});

export const INVENTORY_TRANSACTION_TYPE_LABELS = Object.freeze({
  [INVENTORY_TRANSACTION_TYPES.OPENING_STOCK]: "Opening Stock",
  [INVENTORY_TRANSACTION_TYPES.STOCK_IN]: "Stock In",
  [INVENTORY_TRANSACTION_TYPES.STOCK_OUT]: "Stock Out",
  [INVENTORY_TRANSACTION_TYPES.GOODS_RECEIPT]: "Goods Receipt",
  [INVENTORY_TRANSACTION_TYPES.ADJUSTMENT_INCREASE]: "Adjustment Increase",
  [INVENTORY_TRANSACTION_TYPES.ADJUSTMENT_DECREASE]: "Adjustment Decrease",
  [INVENTORY_TRANSACTION_TYPES.RETURN_IN]: "Return In",
  [INVENTORY_TRANSACTION_TYPES.RETURN_OUT]: "Return Out",
  [INVENTORY_TRANSACTION_TYPES.VOID]: "Void / Reversal",
});

export const INVENTORY_TRANSACTION_DIRECTIONS = Object.freeze({
  IN: "IN",
  OUT: "OUT",
  NEUTRAL: "NEUTRAL",
});

export const INVENTORY_TRANSACTION_DIRECTION_BY_TYPE = Object.freeze({
  [INVENTORY_TRANSACTION_TYPES.OPENING_STOCK]:
    INVENTORY_TRANSACTION_DIRECTIONS.IN,
  [INVENTORY_TRANSACTION_TYPES.STOCK_IN]: INVENTORY_TRANSACTION_DIRECTIONS.IN,
  [INVENTORY_TRANSACTION_TYPES.GOODS_RECEIPT]:
    INVENTORY_TRANSACTION_DIRECTIONS.IN,
  [INVENTORY_TRANSACTION_TYPES.ADJUSTMENT_INCREASE]:
    INVENTORY_TRANSACTION_DIRECTIONS.IN,
  [INVENTORY_TRANSACTION_TYPES.RETURN_IN]: INVENTORY_TRANSACTION_DIRECTIONS.IN,

  [INVENTORY_TRANSACTION_TYPES.STOCK_OUT]: INVENTORY_TRANSACTION_DIRECTIONS.OUT,
  [INVENTORY_TRANSACTION_TYPES.ADJUSTMENT_DECREASE]:
    INVENTORY_TRANSACTION_DIRECTIONS.OUT,
  [INVENTORY_TRANSACTION_TYPES.RETURN_OUT]:
    INVENTORY_TRANSACTION_DIRECTIONS.OUT,

  [INVENTORY_TRANSACTION_TYPES.VOID]: INVENTORY_TRANSACTION_DIRECTIONS.NEUTRAL,
});

export const INVENTORY_TRANSACTION_TYPE_OPTIONS = Object.freeze(
  Object.values(INVENTORY_TRANSACTION_TYPES).map((value) => ({
    value,
    label: INVENTORY_TRANSACTION_TYPE_LABELS[value],
  })),
);

export function isValidInventoryTransactionType(value) {
  return Object.values(INVENTORY_TRANSACTION_TYPES).includes(value);
}

export function getInventoryTransactionTypeLabel(value) {
  return INVENTORY_TRANSACTION_TYPE_LABELS[value] ?? value ?? "Unknown";
}

export function getInventoryTransactionDirection(value) {
  return (
    INVENTORY_TRANSACTION_DIRECTION_BY_TYPE[value] ??
    INVENTORY_TRANSACTION_DIRECTIONS.NEUTRAL
  );
}
