export const REPORT_MIGRATION_ISSUE_TYPES = Object.freeze({
  PRODUCT_MISSING_STOCK_STATUS: "PRODUCT_MISSING_STOCK_STATUS",
  PRODUCT_INCORRECT_STOCK_STATUS: "PRODUCT_INCORRECT_STOCK_STATUS",
  MOVEMENT_MISSING_REPORT_TRANSACTION:
    "MOVEMENT_MISSING_REPORT_TRANSACTION",
  REPORT_TRANSACTION_MISSING_MOVEMENT:
    "REPORT_TRANSACTION_MISSING_MOVEMENT",
  REPORT_TRANSACTION_INVALID_QUANTITIES:
    "REPORT_TRANSACTION_INVALID_QUANTITIES",
  REPORT_TRANSACTION_MISSING_REQUIRED_FIELD:
    "REPORT_TRANSACTION_MISSING_REQUIRED_FIELD",
  PRODUCT_BALANCE_MISMATCH: "PRODUCT_BALANCE_MISMATCH",
  UNSUPPORTED_LEGACY_MOVEMENT: "UNSUPPORTED_LEGACY_MOVEMENT",
});

export const REPORT_MIGRATION_SEVERITIES = Object.freeze({
  INFO: "INFO",
  WARNING: "WARNING",
  ERROR: "ERROR",
  BLOCKER: "BLOCKER",
});

export const REPORT_MIGRATION_STATUSES = Object.freeze({
  READY: "READY",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  BLOCKED: "BLOCKED",
});

export const REPORT_MIGRATION_LIMITS = Object.freeze({
  MAX_PREVIEW_RECORDS: 5000,
});
