import { USER_ROLES } from "../roles";
import { REPORT_TYPES } from "./reportTypes";

export const REPORT_ACTIONS = Object.freeze({
  VIEW: "VIEW",
  EXPORT: "EXPORT",
  PRINT: "PRINT",
  VIEW_VALUATION: "VIEW_VALUATION",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
});

const OPERATIONAL_REPORT_ROLES = Object.freeze([
  USER_ROLES.SUPERADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.INVENTORY_STAFF,
  USER_ROLES.AUDITOR,
]);

const ADMIN_AUDIT_ROLES = Object.freeze([
  USER_ROLES.SUPERADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.AUDITOR,
]);

const VALUATION_ROLES = Object.freeze([
  USER_ROLES.SUPERADMIN,
  USER_ROLES.ADMIN,
  USER_ROLES.AUDITOR,
]);

export const REPORT_PERMISSIONS = Object.freeze({
  [REPORT_TYPES.CURRENT_INVENTORY]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.VIEW_VALUATION]: VALUATION_ROLES,
  }),

  [REPORT_TYPES.STOCK_MOVEMENT]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.STOCK_IN]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.STOCK_OUT]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.STOCK_ADJUSTMENT]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.LOW_STOCK_REORDER]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.INVENTORY_VALUATION]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: VALUATION_ROLES,
    [REPORT_ACTIONS.EXPORT]: VALUATION_ROLES,
    [REPORT_ACTIONS.PRINT]: VALUATION_ROLES,
    [REPORT_ACTIONS.VIEW_VALUATION]: VALUATION_ROLES,
  }),

  [REPORT_TYPES.PRODUCT_LEDGER]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.PURCHASE_SUPPLIER]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.GOODS_RECEIPT]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.EXPORT]: OPERATIONAL_REPORT_ROLES,
    [REPORT_ACTIONS.PRINT]: OPERATIONAL_REPORT_ROLES,
  }),

  [REPORT_TYPES.AUDIT_LOG]: Object.freeze({
    [REPORT_ACTIONS.VIEW]: ADMIN_AUDIT_ROLES,
    [REPORT_ACTIONS.EXPORT]: ADMIN_AUDIT_ROLES,
    [REPORT_ACTIONS.PRINT]: ADMIN_AUDIT_ROLES,
    [REPORT_ACTIONS.VIEW_AUDIT_LOGS]: ADMIN_AUDIT_ROLES,
  }),
});

export function getAllowedRolesForReportAction(
  reportType,
  action = REPORT_ACTIONS.VIEW,
) {
  return REPORT_PERMISSIONS[reportType]?.[action] ?? [];
}

export function canAccessReport(
  role,
  reportType,
  action = REPORT_ACTIONS.VIEW,
) {
  if (!role || !reportType) {
    return false;
  }

  return getAllowedRolesForReportAction(reportType, action).includes(role);
}

export function getAccessibleReportTypes(role, action = REPORT_ACTIONS.VIEW) {
  return Object.keys(REPORT_PERMISSIONS).filter((reportType) =>
    canAccessReport(role, reportType, action),
  );
}
