export const REPORT_TYPES = Object.freeze({
  CURRENT_INVENTORY: "CURRENT_INVENTORY",
  STOCK_MOVEMENT: "STOCK_MOVEMENT",
  STOCK_IN: "STOCK_IN",
  STOCK_OUT: "STOCK_OUT",
  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",
  LOW_STOCK_REORDER: "LOW_STOCK_REORDER",
  INVENTORY_VALUATION: "INVENTORY_VALUATION",
  PRODUCT_LEDGER: "PRODUCT_LEDGER",
  PURCHASE_SUPPLIER: "PURCHASE_SUPPLIER",
  GOODS_RECEIPT: "GOODS_RECEIPT",
  AUDIT_LOG: "AUDIT_LOG",
});
