export const DASHBOARD_CHARTS = Object.freeze({
  MONTHLY_STOCK_IN_OUT: "MONTHLY_STOCK_IN_OUT",
  INVENTORY_VALUE_BY_CATEGORY: "INVENTORY_VALUE_BY_CATEGORY",
  MOST_ISSUED_PRODUCTS: "MOST_ISSUED_PRODUCTS",
  RECENT_STOCK_MOVEMENTS: "RECENT_STOCK_MOVEMENTS",
});

export const DASHBOARD_CHART_LABELS = Object.freeze({
  [DASHBOARD_CHARTS.MONTHLY_STOCK_IN_OUT]: "Monthly Stock In vs Stock Out",
  [DASHBOARD_CHARTS.INVENTORY_VALUE_BY_CATEGORY]: "Inventory Value by Category",
  [DASHBOARD_CHARTS.MOST_ISSUED_PRODUCTS]: "Most Frequently Issued Products",
  [DASHBOARD_CHARTS.RECENT_STOCK_MOVEMENTS]: "Recent Stock Movements",
});

export const DASHBOARD_TIME_RANGES = Object.freeze({
  TODAY: "TODAY",
  LAST_7_DAYS: "LAST_7_DAYS",
  THIS_MONTH: "THIS_MONTH",
  LAST_30_DAYS: "LAST_30_DAYS",
  THIS_YEAR: "THIS_YEAR",
});

export const DASHBOARD_TIME_RANGE_LABELS = Object.freeze({
  [DASHBOARD_TIME_RANGES.TODAY]: "Today",
  [DASHBOARD_TIME_RANGES.LAST_7_DAYS]: "Last 7 Days",
  [DASHBOARD_TIME_RANGES.THIS_MONTH]: "This Month",
  [DASHBOARD_TIME_RANGES.LAST_30_DAYS]: "Last 30 Days",
  [DASHBOARD_TIME_RANGES.THIS_YEAR]: "This Year",
});

export const DASHBOARD_DEFAULT_TIME_RANGE = DASHBOARD_TIME_RANGES.THIS_MONTH;

export const DASHBOARD_CHART_LIMITS = Object.freeze({
  MOST_ISSUED_PRODUCTS: 8,
  RECENT_STOCK_MOVEMENTS: 8,
  CATEGORY_BREAKDOWN: 8,
});
