export const DASHBOARD_METRICS = Object.freeze({
  TOTAL_ACTIVE_PRODUCTS: "TOTAL_ACTIVE_PRODUCTS",
  TOTAL_STOCK_QUANTITY: "TOTAL_STOCK_QUANTITY",
  INVENTORY_VALUE: "INVENTORY_VALUE",
  LOW_STOCK_PRODUCTS: "LOW_STOCK_PRODUCTS",
  OUT_OF_STOCK_PRODUCTS: "OUT_OF_STOCK_PRODUCTS",
  STOCK_RECEIVED_THIS_MONTH: "STOCK_RECEIVED_THIS_MONTH",
  STOCK_RELEASED_THIS_MONTH: "STOCK_RELEASED_THIS_MONTH",
  PENDING_PURCHASE_ORDERS: "PENDING_PURCHASE_ORDERS",
  PENDING_GOODS_RECEIPTS: "PENDING_GOODS_RECEIPTS",
  PENDING_STOCK_ADJUSTMENTS: "PENDING_STOCK_ADJUSTMENTS",
});

export const DASHBOARD_METRIC_LABELS = Object.freeze({
  [DASHBOARD_METRICS.TOTAL_ACTIVE_PRODUCTS]: "Active Products",
  [DASHBOARD_METRICS.TOTAL_STOCK_QUANTITY]: "Available Stock",
  [DASHBOARD_METRICS.INVENTORY_VALUE]: "Inventory Value",
  [DASHBOARD_METRICS.LOW_STOCK_PRODUCTS]: "Low Stock",
  [DASHBOARD_METRICS.OUT_OF_STOCK_PRODUCTS]: "Out of Stock",
  [DASHBOARD_METRICS.STOCK_RECEIVED_THIS_MONTH]: "Stock Received This Month",
  [DASHBOARD_METRICS.STOCK_RELEASED_THIS_MONTH]: "Stock Released This Month",
  [DASHBOARD_METRICS.PENDING_PURCHASE_ORDERS]: "Pending Purchase Orders",
  [DASHBOARD_METRICS.PENDING_GOODS_RECEIPTS]: "Pending Goods Receipts",
  [DASHBOARD_METRICS.PENDING_STOCK_ADJUSTMENTS]: "Pending Adjustments",
});

export const DASHBOARD_METRIC_DESCRIPTIONS = Object.freeze({
  [DASHBOARD_METRICS.TOTAL_ACTIVE_PRODUCTS]:
    "Products currently active in inventory.",
  [DASHBOARD_METRICS.TOTAL_STOCK_QUANTITY]:
    "Total quantity currently available across products.",
  [DASHBOARD_METRICS.INVENTORY_VALUE]:
    "Current inventory value based on quantity and cost.",
  [DASHBOARD_METRICS.LOW_STOCK_PRODUCTS]:
    "Products at or below their reorder level.",
  [DASHBOARD_METRICS.OUT_OF_STOCK_PRODUCTS]:
    "Products with no available quantity.",
  [DASHBOARD_METRICS.STOCK_RECEIVED_THIS_MONTH]:
    "Total inbound quantity posted during the current month.",
  [DASHBOARD_METRICS.STOCK_RELEASED_THIS_MONTH]:
    "Total outbound quantity posted during the current month.",
  [DASHBOARD_METRICS.PENDING_PURCHASE_ORDERS]:
    "Purchase orders still awaiting completion.",
  [DASHBOARD_METRICS.PENDING_GOODS_RECEIPTS]:
    "Goods receipts that are not yet finalized.",
  [DASHBOARD_METRICS.PENDING_STOCK_ADJUSTMENTS]:
    "Adjustment requests awaiting review or posting.",
});

export const DASHBOARD_METRIC_FORMATS = Object.freeze({
  NUMBER: "NUMBER",
  CURRENCY: "CURRENCY",
});

export const DASHBOARD_METRIC_FORMAT_BY_TYPE = Object.freeze({
  [DASHBOARD_METRICS.TOTAL_ACTIVE_PRODUCTS]: DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.TOTAL_STOCK_QUANTITY]: DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.INVENTORY_VALUE]: DASHBOARD_METRIC_FORMATS.CURRENCY,
  [DASHBOARD_METRICS.LOW_STOCK_PRODUCTS]: DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.OUT_OF_STOCK_PRODUCTS]: DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.STOCK_RECEIVED_THIS_MONTH]:
    DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.STOCK_RELEASED_THIS_MONTH]:
    DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.PENDING_PURCHASE_ORDERS]: DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.PENDING_GOODS_RECEIPTS]: DASHBOARD_METRIC_FORMATS.NUMBER,
  [DASHBOARD_METRICS.PENDING_STOCK_ADJUSTMENTS]:
    DASHBOARD_METRIC_FORMATS.NUMBER,
});
